### PR TITLE
Fix response metadata

### LINKED ISSUE #34: Response locked, mismatch number of responses and actual correct responses,
https://github.com/mscheltienne/eeg-flow/blob/37f3e597c1f6511e7ccb9c17b63de0a6089fe8e6/eeg_flow/tasks/epochs_evoked.py#L229

Hello, 
Dans un exemple ou un enregistrement contient des falses alarms (le participant a appuyé alors qu'il n'aurait pas du), 
- metadata_reponse["event_name"] va contenir strictement les evenements "responses" dont les faut
- metadata_reponse["response_time"] ne contient que les bonnes reponses (== Hits)
Donc il y aura par exemple 36 event_name et 35 response_time

Tu arriverais a voir comment filtrer facilement la premiere partie pour retirer ces mauvaises reponses?
Merci

Arthur

https://we.tl/t-Pisv83JNjC

### PR DESCRIPTION
**Pull request by mscheltienne**
Close #34 

The issue seems to be the 1 `FalseAlarms_tooquick` which is not filtered out from the `events_response` array.

This is the response types you have in this file:

```
Counter({'CorrectRejections-standard': 288, 'Hits': 35, 'CorrectRejections-novel': 34, 'FalseAlarms-novel': 2, 'FalseAlarms_tooquick': 1})
```

And the `events_reponse` array is filtered here: https://github.com/mscheltienne/eeg-flow/blob/37f3e597c1f6511e7ccb9c17b63de0a6089fe8e6/eeg_flow/tasks/epochs_evoked.py#L207-L209

Which looks for response events following a target event. The "too quick" condition is missing here.
That PR adds another clause to the filtering of the response events.

### CODE REVIEW

**Comment by mscheltienne** [comment]
@ArthurNguyen Have a look, if it makes sense to you, I'll merge.

**Comment by ArthurNguyen** [comment]
looks good to me thanks!

I've changed the names of the derivatives to separate stimlocked and responselocked

**Comment by mscheltienne** [comment]
What is the difference between 8 and 9?

**Comment by ArthurNguyen** [comment]
argh, great point I will remove 9

**Pull request merged**
